<?php
//只显示server_type=2、3的类别
return array (
  24 =>
  array (
    'id' => '24',
    'parentid' => '0',
    'name' => '查询信息',
    'path' => '#',
    'locality' => '1',
    'isview' => '1',
    'status' => '1',
    'server_type' => 'all',
    'children' =>
    array (
      44 =>
      array (
        'id' => '44',
        'parentid' => '24',
        'name' => '用户列表',
        'path' => APP_SITE_URL . '/admin/user_show_list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '2',
        'has' => 1,
      ),
      45 =>
      array (
        'id' => '45',
        'parentid' => '24',
        'name' => '索引页',
        'path' => 'http://www.zp0.cc/work.html',
//		'path' => APP_SITE_URL . '/admin/user_show_list_all',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      79 =>
      array (
        'id' => '79',
        'parentid' => '24',
        'name' => '社团列表',
        'path' => APP_SITE_URL . '/admin/union_list',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      38 =>
      array (
        'id' => '38',
        'parentid' => '24',
        'name' => '公司-社团关系表',
        'path' => APP_SITE_URL . '/admin/company_union_list',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      27 =>
      array (
        'id' => '30',
        'parentid' => '24',
        'name' => '招聘录入',
        'path' => APP_SITE_URL . '/admin/recruit_insert',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '3',
        'has' => 1,
      ),
      /*28 =>
      array (
        'id' => '28',
        'parentid' => '24',
        'name' => '舶来录入',
        'path' => APP_SITE_URL . '/admin/welcome_insert',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '3',
        'has' => 1,
      ),*/
      29 =>
      array (
        'id' => '29',
        'parentid' => '24',
        'name' => '创建招聘分类',
        'path' => APP_SITE_URL . '/admin/create_recruit_tag',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '3',
        'has' => 1,
      ),
      81 =>
      array (
        'id' => '81',
        'parentid' => '24',
        'name' => '荔枝币流水',
        'path' => APP_SITE_URL . '/admin/money_list',
        'locality' => '6',
        'isview' => '1',
        'status' => '1',
        'server_type' => '2',
        'has' => 1,
      ),
      82 =>
      array (
        'id' => '82',
        'parentid' => '24',
        'name' => '总荔枝币流水',
        'path' => APP_SITE_URL . '/admin/money_list_all',
        'locality' => '7',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      83 =>
      array (
        'id' => '83',
        'parentid' => '24',
        'name' => '创建舶来帐号',
        'path' => APP_SITE_URL . '/admin/create_user_welcome',
        'locality' => '8',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      84 =>
      array (
        'id' => '84',
        'parentid' => '24',
        'name' => '群福利发奖',
        'path' => APP_SITE_URL . '/admin/send_group_award',
        'locality' => '8',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      85 =>
      array (
        'id' => '85',
        'parentid' => '24',
        'name' => '职位列表',
        'path' => APP_SITE_URL . '/admin/jd_position_list_all',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      86 =>
      array (
        'id' => '86',
        'parentid' => '24',
        'name' => '关键词-岗位职责列表',
        'path' => APP_SITE_URL . '/admin/jd_position_keyword_list/describe',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      87 =>
      array (
        'id' => '87',
        'parentid' => '24',
        'name' => '关键词-任职资格列表',
        'path' => APP_SITE_URL . '/admin/jd_position_keyword_list/demand',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      88 =>
      array (
        'id' => '88',
        'parentid' => '24',
        'name' => '职位描述列表',
        'path' => APP_SITE_URL . '/admin/jd_position_describe_list/',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      89 =>
      array (
        'id' => '89',
        'parentid' => '24',
        'name' => '职位列表批量导入',
        'path' => APP_SITE_URL . '/admin/jd_position_import_batch/',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      90 =>
      array (
        'id' => '90',
        'parentid' => '24',
        'name' => 'JD-基础信息录入',
        'path' => APP_SITE_URL . '/admin/jd_base_insert',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      91 =>
      array (
        'id' => '91',
        'parentid' => '24',
        'name' => 'JD-基础信息列表',
        'path' => APP_SITE_URL . '/admin/jd_base_list',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      92 =>
      array (
        'id' => '92',
        'parentid' => '24',
        'name' => 'JD-批量导入',
        'path' => APP_SITE_URL . '/admin/jd_list_import_batch/',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      93 =>
      array (
        'id' => '93',
        'parentid' => '24',
        'name' => '简历-基础信息录入',
        'path' => APP_SITE_URL . '/admin/jd_resume_insert',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      94 =>
      array (
        'id' => '94',
        'parentid' => '24',
        'name' => '简历-基础信息列表',
        'path' => APP_SITE_URL . '/admin/jd_resume_list',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      95 =>
      array (
        'id' => '95',
        'parentid' => '24',
        'name' => '简历-批量导入',
        'path' => APP_SITE_URL . '/admin/resume_import_batch/',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10',
        'has' => 1,
      ),
      96 =>
          array (
              'id' => '96',
              'parentid' => '24',
              'name' => '对接列表',
              'path' => APP_SITE_URL . '/admin/jd_supply_list',
              'locality' => '2',
              'isview' => '1',
              'status' => '1',
              'server_type' => '10',
              'has' => 1,
          ),
    ),
    'has' => 1,
  ),
  53 =>
  array (
    'id' => '53',
    'parentid' => '0',
    'name' => '充值相关',
    'path' => '#',
    'locality' => '1',
    'isview' => '1',
    'status' => '1',
    'server_type' => 'all',
    'children' =>
    array (
      46 =>
      array (
        'id' => '46',
        'parentid' => '53',
        'name' => '每日充值统计',
        'path' => '/pay/day-pay/show-list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      85 =>
      array (
        'id' => '85',
        'parentid' => '53',
        'name' => '平台每日充值汇总',
        'path' => '/platform/day-pay-stat/show-list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      70 =>
      array (
        'id' => '70',
        'parentid' => '53',
        'name' => '每日充值明细相关',
        'path' => '/center/day-pay-series/charge-by-day',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      71 =>
      array (
        'id' => '71',
        'parentid' => '53',
        'name' => '每日充值相关',
        'path' => '/center/day-pay-series/daily-recharge-details',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      47 =>
      array (
        'id' => '47',
        'parentid' => '53',
        'name' => '玩家储值',
        'path' => '/pay/role-recharge/show-list',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      86 =>
      array (
        'id' => '86',
        'parentid' => '53',
        'name' => '平台每日汇总',
        'path' => '/platform/day-summary/show-list',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      48 =>
      array (
        'id' => '48',
        'parentid' => '53',
        'name' => '充值金额段比例',
        'path' => '/pay/prorate/show-list',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      72 =>
      array (
        'id' => '72',
        'parentid' => '53',
        'name' => '每月充值相关',
        'path' => '/center/day-pay-series/daily-recharge-month',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      49 =>
      array (
        'id' => '49',
        'parentid' => '53',
        'name' => '充值等级汇总',
        'path' => '/pay/level-collect/show-list',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      73 =>
      array (
        'id' => '73',
        'parentid' => '53',
        'name' => '充值实时对比',
        'path' => '/center/day-pay-series/real-time-compare',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      75 =>
      array (
        'id' => '75',
        'parentid' => '53',
        'name' => '充值排行',
        'path' => '/pay/charge-list/show-list',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      99 =>
      array (
        'id' => '99',
        'parentid' => '53',
        'name' => '所有充值明细（即时）',
        'path' => '/recharge/recharge/recharge-detail',
        'locality' => '16',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      100 =>
      array (
        'id' => '100',
        'parentid' => '53',
        'name' => '新增充值用户',
        'path' => '/pay/new-pay-user/show-list',
        'locality' => '17',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      101 =>
      array (
        'id' => '101',
        'parentid' => '53',
        'name' => '充值用户排行榜',
        'path' => '/pay/stat-pay-list/show-list',
        'locality' => '18',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
    ),
    'has' => 1,
  ),
  65 =>
  array (
    'id' => '65',
    'parentid' => '0',
    'name' => '全服控制',
    'path' => '#',
    'locality' => '1',
    'isview' => '1',
    'status' => '1',
    'server_type' => 'all',
    'children' =>
    array (
      87 =>
      array (
        'id' => '87',
        'parentid' => '65',
        'name' => '平台循环消息',
        'path' => '/platform/cycle-message/show-list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      146 =>
      array (
        'id' => '146',
        'parentid' => '65',
        'name' => '雪2新活动设置',
        'path' => '/platform/demo-active/show-list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      144 =>
      array (
        'id' => '144',
        'parentid' => '65',
        'name' => '查看分服登陆数',
        'path' => '/platform/get-server-stats/show-list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      143 =>
      array (
        'id' => '143',
        'parentid' => '65',
        'name' => '全服模板更新',
        'path' => '/platform/execute-query/template-index',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      140 =>
      array (
        'id' => '140',
        'parentid' => '65',
        'name' => '媒体礼包',
        'path' => '/center/card-num',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      74 =>
      array (
        'id' => '74',
        'parentid' => '65',
        'name' => '全服SQL执行',
        'path' => '/platform/execute-query/index',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      88 =>
      array (
        'id' => '88',
        'parentid' => '65',
        'name' => '内部人员管理',
        'path' => '/platform/inter-person/show-list',
        'locality' => '2',
        'isview' => '0',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      89 =>
      array (
        'id' => '89',
        'parentid' => '65',
        'name' => '平台怪物掉落设置',
        'path' => '/platform/monster/show-list',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      90 =>
      array (
        'id' => '90',
        'parentid' => '65',
        'name' => '平台玩家建议',
        'path' => '/platform/role-suggest/show-list',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      124 =>
      array (
        'id' => '124',
        'parentid' => '65',
        'name' => '配置管理',
        'path' => '/gm/config-reason/config-reason',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      137 =>
      array (
        'id' => '137',
        'parentid' => '65',
        'name' => 'GM配置文件修改',
        'path' => '/permission/server/fix-gm-config',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      138 =>
      array (
        'id' => '138',
        'parentid' => '65',
        'name' => '启服务控制',
        'path' => '/platform/execute-query/control',
        'locality' => '6',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      91 =>
      array (
        'id' => '91',
        'parentid' => '65',
        'name' => '平台节日活动',
        'path' => '/platform/festival-activity/show-list',
        'locality' => '6',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      92 =>
      array (
        'id' => '92',
        'parentid' => '65',
        'name' => '平台优惠活动',
        'path' => '/platform/favorable-activity/show-list',
        'locality' => '7',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      118 =>
      array (
        'id' => '118',
        'parentid' => '65',
        'name' => '全服Hosts同步',
        'path' => '/platform/execute-query/hosts',
        'locality' => '8',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      121 =>
      array (
        'id' => '121',
        'parentid' => '65',
        'name' => '数据库地址',
        'path' => '/platform/execute-query/php-my-admin-list',
        'locality' => '9',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      122 =>
      array (
        'id' => '122',
        'parentid' => '65',
        'name' => 'VIP等级奖励发放',
        'path' => '/platform/favorable-vip-level/show-list',
        'locality' => '10',
        'isview' => '0',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      135 =>
      array (
        'id' => '135',
        'parentid' => '65',
        'name' => '达到发奖励',
        'path' => '/platform/favorable-reach-send/show-list',
        'locality' => '11',
        'isview' => '0',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      136 =>
      array (
        'id' => '136',
        'parentid' => '65',
        'name' => '宠物日志统计',
        'path' => '/pet/pet-statistics',
        'locality' => '20',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
    ),
    'has' => 1,
  ),
  125 =>
  array (
    'id' => '125',
    'parentid' => '0',
    'name' => '玩家概况',
    'path' => '#',
    'locality' => '1',
    'isview' => '1',
    'status' => '1',
    'server_type' => '1',
    'children' =>
    array (
      126 =>
      array (
        'id' => '126',
        'parentid' => '125',
        'name' => '注册登录',
        'path' => '/gamer/gamer/stat-login-out',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      145 =>
      array (
        'id' => '145',
        'parentid' => '125',
        'name' => '单服封IP',
        'path' => '/searchuser/ip-control/show-list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      128 =>
      array (
        'id' => '128',
        'parentid' => '125',
        'name' => '实时等级分布',
        'path' => '/gamer/stat-userlevel-spread/stat-userlevel-spread',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      129 =>
      array (
        'id' => '129',
        'parentid' => '125',
        'name' => '在线时长',
        'path' => '/gamer/stat-online-long/stat-online-long',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      132 =>
      array (
        'id' => '132',
        'parentid' => '125',
        'name' => '新老玩家汇总',
        'path' => '/gamer/new-old-sign-login-compare/new-old-sign-login-compare',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      130 =>
      array (
        'id' => '130',
        'parentid' => '125',
        'name' => '人物游戏分布',
        'path' => '/gamer/game-distribute/game-distribute',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      131 =>
      array (
        'id' => '131',
        'parentid' => '125',
        'name' => '等级分布',
        'path' => '/gamer/stat-userlevel-count/stat-userlevel-count?laction=all',
        'locality' => '6',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      133 =>
      array (
        'id' => '133',
        'parentid' => '125',
        'name' => '每日汇总（单服）',
        'path' => '/gamer/stat-seloneday/stat-seloneday?newtype=sel',
        'locality' => '6',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      112 =>
      array (
        'id' => '112',
        'parentid' => '125',
        'name' => '实时在线数据',
        'path' => '/operation/online/timely-online',
        'locality' => '24',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
    ),
    'has' => 1,
  ),
  52 =>
  array (
    'id' => '52',
    'parentid' => '0',
    'name' => '平台总服控制',
    'path' => '#',
    'locality' => '2',
    'isview' => '1',
    'status' => '1',
    'server_type' => 'all',
    'children' =>
    array (
      57 =>
      array (
        'id' => '57',
        'parentid' => '52',
        'name' => '活动控制',
        'path' => '/alltake/activity/manage',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      59 =>
      array (
        'id' => '59',
        'parentid' => '52',
        'name' => 'GM权限',
        'path' => '/gm/setting/gm-permission',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      60 =>
      array (
        'id' => '60',
        'parentid' => '52',
        'name' => '前台设置',
        'path' => '/gm/setting/system-foreward',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
    ),
    'has' => 1,
  ),
  54 =>
  array (
    'id' => '54',
    'parentid' => '0',
    'name' => '在线相关',
    'path' => '#',
    'locality' => '2',
    'isview' => '1',
    'status' => '1',
    'server_type' => 'all',
    'children' =>
    array (
      55 =>
      array (
        'id' => '55',
        'parentid' => '54',
        'name' => '每日在线',
        'path' => '/center/online/count-day',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      134 =>
      array (
        'id' => '134',
        'parentid' => '54',
        'name' => '在线数据图表',
        'path' => '/gamer/stat-online-new/online-new-xml',
        'locality' => '2',
        'isview' => '0',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      56 =>
      array (
        'id' => '56',
        'parentid' => '54',
        'name' => '每日分时在线',
        'path' => '/center/online/count-minu',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '10000',
        'has' => 1,
      ),
      36 =>
      array (
        'id' => '36',
        'parentid' => '54',
        'name' => '在线数据',
        'path' => '/role/online/online-day',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
    ),
    'has' => 1,
  ),
  10 =>
  array (
    'id' => '10',
    'parentid' => '0',
    'name' => '物品相关',
    'path' => '#',
    'locality' => '4',
    'isview' => '1',
    'status' => '1',
    'server_type' => 'all',
    'children' =>
    array (
      93 =>
      array (
        'id' => '93',
        'parentid' => '10',
        'name' => '平台商城物品管理',
        'path' => '/platform/mall-goods/show-list',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      94 =>
      array (
        'id' => '94',
        'parentid' => '10',
        'name' => '平台商城特惠物品',
        'path' => '/platform/mall-privilege/show-list',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      23 =>
      array (
        'id' => '23',
        'parentid' => '10',
        'name' => '物品强化',
        'path' => '/items/enchantments/item-enchantments',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      43 =>
      array (
        'id' => '43',
        'parentid' => '10',
        'name' => '_____占星操作(无该功能)',
        'path' => '/items/astrology/astrology-option',
        'locality' => '3',
        'isview' => '0',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      95 =>
      array (
        'id' => '95',
        'parentid' => '10',
        'name' => '平台奖励发放',
        'path' => '/platform/reward-send/index',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      80 =>
      array (
        'id' => '80',
        'parentid' => '10',
        'name' => '物品日志',
        'path' => '/items/consume/show-use',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      123 =>
      array (
        'id' => '123',
        'parentid' => '10',
        'name' => '商城定时更新',
        'path' => '/platform/mall-goods-update/update-edit',
        'locality' => '11',
        'isview' => '0',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
    ),
    'has' => 1,
  ),
  40 =>
  array (
    'id' => '40',
    'parentid' => '0',
    'name' => 'GM控制',
    'path' => '#',
    'locality' => '50',
    'isview' => '1',
    'status' => '1',
    'server_type' => 'all',
    'children' =>
    array (
      41 =>
      array (
        'id' => '41',
        'parentid' => '40',
        'name' => '活动控制',
        'path' => '/gm/activity',
        'locality' => '1',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      51 =>
      array (
        'id' => '51',
        'parentid' => '40',
        'name' => '奖励发放',
        'path' => '/gm/reward-send',
        'locality' => '2',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      42 =>
      array (
        'id' => '42',
        'parentid' => '40',
        'name' => '循环消息',
        'path' => '/gm/looping-message',
        'locality' => '3',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      61 =>
      array (
        'id' => '61',
        'parentid' => '40',
        'name' => '内部人员',
        'path' => '/gm/internal-player',
        'locality' => '4',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      62 =>
      array (
        'id' => '62',
        'parentid' => '40',
        'name' => 'GM元宝充值',
        'path' => '/gm/goldsend',
        'locality' => '5',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      69 =>
      array (
        'id' => '69',
        'parentid' => '40',
        'name' => '测试登录',
        'path' => '/gm/login-game',
        'locality' => '6',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      63 =>
      array (
        'id' => '63',
        'parentid' => '40',
        'name' => '清档',
        'path' => '/gm/setting/truncate-tables',
        'locality' => '6',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      58 =>
      array (
        'id' => '58',
        'parentid' => '40',
        'name' => '捞人',
        'path' => '/gm/setting/get-person',
        'locality' => '8',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      102 =>
      array (
        'id' => '102',
        'parentid' => '40',
        'name' => '平台双倍经验设置',
        'path' => '/platform/double-experience/show-list',
        'locality' => '9',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      103 =>
      array (
        'id' => '103',
        'parentid' => '40',
        'name' => '用户解锁',
        'path' => '/searchuser/user-unlock/show-list',
        'locality' => '10',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      109 =>
      array (
        'id' => '109',
        'parentid' => '40',
        'name' => '平台封号',
        'path' => '/platform/role-char-action/show-list',
        'locality' => '11',
        'isview' => '1',
        'status' => '1',
        'server_type' => '0',
        'has' => 1,
      ),
      111 =>
      array (
        'id' => '111',
        'parentid' => '40',
        'name' => '模拟充值',
        'path' => '/payauto/insert-order/show-list',
        'locality' => '12',
        'isview' => '1',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
      113 =>
      array (
        'id' => '113',
        'parentid' => '40',
        'name' => '禁言封号改名',
        'path' => '/searchuser/char-action',
        'locality' => '13',
        'isview' => '0',
        'status' => '1',
        'server_type' => '1',
        'has' => 1,
      ),
    ),
    'has' => 1,
  ),
);
?>